<?php

/**
 * BaseBudgetTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $budget_id
 * @property integer $tag_id
 * @property Budget $Budget
 * @property Tag $Tag
 * 
 * @method integer   getBudgetId()  Returns the current record's "budget_id" value
 * @method integer   getTagId()     Returns the current record's "tag_id" value
 * @method Budget    getBudget()    Returns the current record's "Budget" value
 * @method Tag       getTag()       Returns the current record's "Tag" value
 * @method BudgetTag setBudgetId()  Sets the current record's "budget_id" value
 * @method BudgetTag setTagId()     Sets the current record's "tag_id" value
 * @method BudgetTag setBudget()    Sets the current record's "Budget" value
 * @method BudgetTag setTag()       Sets the current record's "Tag" value
 * 
 * @package    moneytalks
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBudgetTag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('budget_tag');
        $this->hasColumn('budget_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('tag_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Budget', array(
             'local' => 'budget_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Tag', array(
             'local' => 'tag_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}