<?php

/**
 * Account
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    moneytalks
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Account extends BaseAccount
{

    public function recalculateBalance()
    {
        $balance = 0;

        foreach ($this->Actions as $action) {
            $deposit = $action->fetchDeposit();

            if ($deposit) {
                $balance += $deposit;
            }

            $withdrawal = $action->fetchWithdrawal();

            if ($withdrawal) {
                $balance -= $withdrawal;
            }
        }

        $this->storeBalance($balance);
    }

    public function fetchBalance()
    {
        //TODO: decrypt this
        return $this->balance;
    }

    public function storeBalance($balance)
    {
        //TODO: encrypt this
        $this->balance = $balance;
        $this->save();
    }

}
