<?php

/**
 * Account
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    moneytalks
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Account extends BaseAccount
{

    public function recalculateBalance($key)
    {
        $balance = 0;

        foreach ($this->Actions as $action) {
            $deposit = $action->fetchDeposit($key);

            if ($deposit) {
                $balance += $deposit;
            }

            $withdrawal = $action->fetchWithdrawal($key);

            if ($withdrawal) {
                $balance -= $withdrawal;
            }
        }

        $this->storeBalance($balance, $key);
    }

    public function fetchBalance($key)
    {
        return CryptHelper::getInstance()->setKey($key)
            ->decrypt($this->balance);
    }

    public function storeBalance($balance, $key)
    {
        $this->balance = CryptHelper::getInstance()->setKey($key)
            ->encrypt($balance);

        $this->save();
    }

}
