<?php

/**
 * ActionTagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActionTagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActionTagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActionTag');
    }
}