<?php

/**
 * Action
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    moneytalks
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Action extends BaseAction
{
    
    public function fetchDeposit($key)
    {
        if (empty($this->deposit)) {
            return 0;
        } else {
            return CryptHelper::getInstance()->setKey($key)
                ->decrypt($this->deposit);
        }
    }

    public function storeDeposit($deposit, $key)
    {
        $this->deposit = CryptHelper::getInstance()->setKey($key)
            ->encrypt($deposit);

        $this->save();
    }

    public function fetchWithdrawal($key)
    {
        if (empty($this->withdrawal)) {
            return 0;
        } else {
            return CryptHelper::getInstance()->setKey($key)
                ->decrypt($this->withdrawal);
        }
    }

    public function storeWithdrawal($withdrawal, $key)
    {
        $this->withdrawal = CryptHelper::getInstance()->setKey($key)
            ->encrypt($withdrawal);

        $this->save();
    }

    public function fetchBalance($key)
    {
        if (empty($this->balance)) {
            return 0;
        } else {
            return CryptHelper::getInstance()->setKey($key)
                ->decrypt($this->balance);
        }
    }

    public function storeBalance($balance, $key)
    {
        $this->balance = CryptHelper::getInstance()->setKey($key)
            ->encrypt($balance);

        $this->save();
    }

}
