<?php

/**
 * Budget
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    moneytalks
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Budget extends BaseBudget
{

    public function fetchAmount($key)
    {
        if (empty($this->amount)) {
            return 0;
        } else {
            return CryptHelper::getInstance()->setKey($key)
                ->decrypt($this->amount);
        }
    }

    public function storeAmount($amount, $key)
    {
        $this->amount = CryptHelper::getInstance()->setKey($key)
            ->encrypt($amount);

        $this->save();
    }

}
