<?php

/**
 * BudgetMonthTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BudgetMonthTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BudgetMonthTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BudgetMonth');
    }
}