<?php

/**
 * BudgetTagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BudgetTagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BudgetTagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BudgetTag');
    }
}