<?php

/**
 * TagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tag');
    }

    static public function fetchUserTags($userId)
    {
        $q = Doctrine_Query::create()
            ->select('t.name')
            ->from('Tag t')
            ->where('t.user_id = ?', $userId)
            ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY);

        if ($q->count()) {
            $tags = array();    
            
            $results = $q->execute();

            foreach ($results as $result) {
                $tags[] = $result['name'];
            }

            return '["'. implode('", "', $tags) . '"]';
        } else {
            return '[]';
        }
    }

}
