# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

homepage:
  url:   /
  param: { module: page, action: home }

about:
  url: /about
  param: { module: page, action: about }

contact:
  url: /contact
  param: { module: page, action: contact }

openid_login:
  url: /openid-login
  param: { module: sfGuardAuth, action: login }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
